preferred-supported-locales: [en, fa, ja, it]
synthetic-package: false
output-dir: ./lib/src/l10n/generated
arb-dir: ./lib/src/l10n
template-arb-file: intl_en.arb
output-localization-file: shopping_cart_localizations.dart
output-class: ShoppingCartLocalizations